### ISSUE TITLE
unable to create a DataKit project

### ISSUE THREAD

**Issue by Ice-Coffey** [stanfordjournalism/stanford-progj-2020#12]
johncoffey$ datakit project create
Creating project from template: gh:stanfordjournalism/cookiecutter-stanford-progj
You've downloaded /Users/johncoffey/.cookiecutters/cookiecutter-stanford-progj before. Is it okay to delete and re-download it? [yes]: 
Select repo_type:
1 - Assignment
2 - Exercise
3 - Project
Choose from 1, 2, 3 [1]: 
project_number_or_shortname []: 1
project_name [COMM 177P Assignment 1]: 
project_short_description [TK]: FDIC failed banks shell script
repo_root [comm-177p-assignment-1]: 
full_name [John Coffey]: 
email [jcoffey2@stanford.edu]: 

~~ Create a Github repo for this project ~~

Traceback (most recent call last):
  File "/var/folders/t3/dhbf69ns29lbptbrrwkxyk8c0000gn/T/tmpdhw_552e.py", line 25, in <module>
    integrate_choices = cmd.run(argparse.ArgumentParser())
  File "/usr/local/lib/python3.7/site-packages/cliff/command.py", line 187, in run
    return_code = self.take_action(parsed_args) or 0
  File "/usr/local/lib/python3.7/site-packages/datakit_github/commands/integrate.py", line 32, in take_action
    account = self.choose_account(api_key)
  File "/usr/local/lib/python3.7/site-packages/datakit_github/commands/integrate.py", line 62, in choose_account
    accounts = GithubApi.accounts(api_key)
  File "/usr/local/lib/python3.7/site-packages/datakit_github/github_api.py", line 12, in accounts
    orgs = [org for org in user.get_orgs()]
  File "/usr/local/lib/python3.7/site-packages/datakit_github/github_api.py", line 12, in <listcomp>
    orgs = [org for org in user.get_orgs()]
  File "/usr/local/lib/python3.7/site-packages/github/PaginatedList.py", line 62, in __iter__
    newElements = self._grow()
  File "/usr/local/lib/python3.7/site-packages/github/PaginatedList.py", line 74, in _grow
    newElements = self._fetchNextPage()
  File "/usr/local/lib/python3.7/site-packages/github/PaginatedList.py", line 205, in _fetchNextPage
    "GET", self.__nextUrl, parameters=self.__nextParams, headers=self.__headers
  File "/usr/local/lib/python3.7/site-packages/github/Requester.py", line 322, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/usr/local/lib/python3.7/site-packages/github/Requester.py", line 345, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.BadCredentialsException: 401 {"message": "Bad credentials", "documentation_url": "https://developer.github.com/v3"}
Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)

**Comment by zstumgoren** [comment]
@Ice-Coffey If memory serves this stemmed from the presence of multiple ssh keys and related GitHub accounts. Sounds like the manual upload approach is working, so going to close this for now. Feel free to re-open if you've found an alternative solution that we should document.
