### ISSUE TITLE
SyntaxError: unexpected EOF while parsing in creating a Github repo

### ISSUE THREAD

**Issue by himchanjung** [stanfordjournalism/stanford-progj-2020#9]
I was creating a Github repo, but I encountered this error:
```
Repo will be created on account: himchanjung
Is this correct? y/n [y]:  
Traceback (most recent call last):
  File "/tmp/tmp2gHXlf.py", line 25, in <module>
    integrate_choices = cmd.run(argparse.ArgumentParser())
  File "/home/jwongi/.local/lib/python2.7/site-packages/cliff/command.py", line 187, in run
    return_code = self.take_action(parsed_args) or 0
  File "/home/jwongi/.local/lib/python2.7/site-packages/datakit_github/commands/integrate.py", line 33, in take_action
    confirm = self.confirm_account_choice(account)
  File "/home/jwongi/.local/lib/python2.7/site-packages/datakit_github/commands/integrate.py", line 86, in confirm_account_choice
    choice = ask("Is this correct? y/n [y]: ").strip().lower()
  File "/home/jwongi/.local/lib/python2.7/site-packages/datakit_github/commands/integrate.py", line 10, in ask
    return input(question)
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```

Is there any way I can resolve this SyntaxError?

**Comment by zstumgoren** [comment]
Hey @himchanjung it looks like you're using python 2.7, which could be one potential source of the issue. Can you try updating your system Python by following [these instructions](https://github.com/stanfordjournalism/stanford-progj-2020/blob/master/docs/tech_setup.md#linux-1)? 

Once you get through that, try re-installing the DataKit libraries again:

```
curl -s https://raw.githubusercontent.com/stanfordjournalism/cookiecutter-stanford-progj/master/requirements.txt | xargs pip install
```

Then try running `datakit project create` and let me know if you still get the error.

**Comment by himchanjung** [comment]
@zstumgoren It worked like magic. I think I forgot to put python3 as global setting.
